# Generated by Django 5.2.4 on 2025-07-31 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Состав заказа', 'verbose_name_plural': 'Состав заказов'},
        ),
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.discount', verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.tax', verbose_name='Налог'),
        ),
    ]
