services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "make migrate && make prod-run"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com

volumes:
  db_data: